
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - jpeg=9e=h166bdaf_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=16_linux64_openblas
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.5.2=py39h700656a_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - numpy=1.22.3=py39hc58783e_2
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.4.2=py39h1832856_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=2_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.3=hc2a1206_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=78.1.1=py39h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - statsmodels=0.13.2=py39hce5d2b2_0
  - tk=8.6.15=h54e0aa7_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - absl-py==2.3.1
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - contourpy==1.3.0
      - cryptography==45.0.7
      - ddu-dirty-mnist==1.1.1
      - dill==0.3.4
      - filelock==3.13.1
      - fonttools==4.59.2
      - fsspec==2024.6.1
      - grpcio==1.74.0
      - h5py==3.14.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.4
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - loguru==0.7.3
      - markdown==3.9
      - markupsafe==2.1.5
      - matplotlib==3.5.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - multimethod==2.0
      - multiprocess==0.70.12.2
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.5.5.64
      - opt-einsum==3.4.0
      - pathos==0.2.8
      - pillow==11.0.0
      - ply==3.11
      - pox==0.3.6
      - ppft==1.7.7
      - protobuf==6.32.1
      - psutil==7.0.0
      - pycparser==2.23
      - pylatexenc==2.10
      - pyparsing==3.2.4
      - pyspnego==0.12.0
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - qiskit==0.38.0
      - qiskit-aer==0.11.0
      - qiskit-ibmq-provider==0.19.2
      - qiskit-terra==0.21.2
      - requests==2.32.5
      - requests-ntlm==1.3.0
      - retworkx==0.16.0
      - rustworkx==0.16.0
      - scikit-learn==1.0.2
      - scipy==1.11.4
      - stevedore==5.5.0
      - symengine==0.14.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorpack==0.11
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.5.1+cu121
      - torchpack==0.3.1
      - torchquantum==0.1.7
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - triton==3.1.0
      - tweedledum==1.1.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - zipp==3.23.0

